name: ecommerce_app
description: A simplified e-commerce mobile app

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6
  image_picker: ^1.0.4
  cached_network_image: ^3.2.3
  shared_preferences: ^2.2.1
  flutter_email_sender: ^6.0.1
  flutter_application_1: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true